org.gradle.parallel=true
org.gradle.caching=true

group=me.nettee
version=0.1.0

# notification
notification=:notification
notificationApi=:notification:notification-api
notificationDomain=:notification:notification-api:notification-domain
notificationException=:notification:notification-api:notification-exception
notificationReadModel=:notification:notification-api:notification-readmodel
notificationApplication=:notification:notification-application
notificationRdbAdapter=:notification:notification-rdb-adapter
notificationWebMvcAdapter=:notification:notification-webmvc