org.gradle.parallel=true
org.gradle.caching=true

group=me.nettee
version=0.1.0

# article
article=:article
articleApi=:article:article-api
articleDomain=:article:article-api:article-domain
articleException=:article:article-api:article-exception
articleReadModel=:article:article-api:article-readmodel
articleApplication=:article:article-application
articleRdbAdapter=:article:article-rdb-adapter
articleWebMvcAdapter=:article:article-webmvc

# series
series=:series
seriesApi=:series:series-api
seriesDomain=:series:series-api:series-domain
seriesException=:series:series-api:series-exception
seriesReadModel=:series:series-api:series-readmodel
seriesApplication=:series:series-application
seriesRdbAdapter=:series:series-rdb-adapter
seriesWebMvcAdapter=:series:series-webmvc

# draft
draft=:draft
draftApi=:draft:draft-api
draftDomain=:draft:draft-api:draft-domain
draftException=:draft:draft-api:draft-exception
draftReadModel=:draft:draft-api:draft-readmodel
draftApplication=:draft:draft-application
draftRdbAdapter=:draft:draft-rdb-adapter
draftWebMvcAdapter=:draft:draft-webmvc