org.gradle.parallel=true
org.gradle.caching=true

group=me.nettee
version=0.1.0

# article
article=:article
articleApi=:article:article-api
articleDomain=:article:article-api:article-domain
articleException=:article:article-api:article-exception
articleReadModel=:article:article-api:article-readmodel
articleApplication=:article:article-application
articleRdbAdapter=:article:article-rdb-adapter
articleWebMvcAdapter=:article:article-webmvc

# auth
auth=:auth
authApi=:auth:auth-api
authDomain=:auth:auth-api:auth-domain
authException=:auth:auth-api:auth-exception
authReadModel=:auth:auth-api:auth-readmodel
authApplication=:auth:auth-application
authRdbAdapter=:auth:auth-rdb-adapter
authWebMvcAdapter=:auth:auth-webmvc

# series
series=:series
seriesApi=:series:series-api
seriesDomain=:series:series-api:series-domain
seriesException=:series:series-api:series-exception
seriesReadModel=:series:series-api:series-readmodel
seriesApplication=:series:series-application
seriesRdbAdapter=:series:series-rdb-adapter
seriesWebMvcAdapter=:series:series-webmvc