spring:
  datasource:
    url: ${BOARD_POSTGRESQL_URL:jdbc:postgresql://localhost:5433/demo}
    username: ${BOARD_POSTGRESQL_USERNAME:root}
    password: ${BOARD_POSTGRESQL_PASSWORD:root}

  data:
    redis:
      host: ${REDIS_URL:127.0.0.1}
      port: ${REDIS_PORT:6379}

  flyway:
    locations:
      - db/migration/v1_0
      - db/migration/local
